### ISSUE TITLE
Compute-to-Data cost is partly unknown before a job starts

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/multi-repo-issue#12]
AlexC: When starting compute, specify no of slots (hours, etc) and transfer that amount of tokens. Ocean-lib will transfer multiple tokens for multiple slots. 

That is option (1) in the [comment below](https://github.com/oceanprotocol/multi-repo-issue/issues/12#issuecomment-833319873). The comment gives other options too. Though (1) seems like the best near term choice.

**Comment by w1kke** [comment]
After a talk with @trentmc yesterday I want to explain the use case of DataUnion.app here to help with understanding the requirements. I think our use case will be interesting for other projects as well.

Our data sale will happen over our Data Portal - think about it like an image gallery with additional functionalities.

First use case:
The users can select images and add them to their selected dataset for algorithm training or validation. => this is a dynamic factor in the price calculation
They then select an algorithm they want to train or validate and metadata for it (e.g. hyperparameter optimisation). => this is a dynamic factor in the price calculation as this configuration does not have the same price for all selections
The users can then select the amount of GPUs/the time until when they want to have the result => this is another dynamic factor in the price calculation

Then the users pay via our liquidity pool and the job is executed in the backend. The time to finish also depends on the dynamic configuration of the job. The billing for this job cannot be 1 datatoken as the costs are variable. A streaming payment would mean that in the middle of the execution the payment wallet could be empty and that would screw the reward for the contributors so a payment upfront is required.

I am thinking about getting a grant for this or co-developing it with deltaDAO. In the end the data that this is applied to do not have to be images but could be anything. But the gallery style of data selection and the job configuration itself is a rather generic process that I think many future users of Ocean Protocol want to mimic.

Second use case:
A user or our system orders the application of an algorithm in our Data Portal on some data that is available in there. The algorithm can have dynamic runtime as it is dependent on the configuration of the algorithm as well as the amount of data and the GPU/compute ordered for it. This is very much in line with the normal application of compute to data but the billing here also cannot be 1 datatoken as the costs are variable. A streaming payment would mean that in the middle of the execution the payment wallet could be empty and that would screw the reward for the contributors so a payment upfront is required.

What do you think about this? @alexcos20 @kremalicious @trentmc

**Comment by trentmc** [comment]
Thanks for elaborating on the use cases and specs, @w1kke. 

Here are some approaches, in increasing order of work needed to support. I recommend (1) because it's simple and possible with the Ocean backend tech today. (This was also Alex's suggestion.)

1. **ERC20, transfer upper bound estimate, and get change.** "1 datatoken gives you 1 min worth of compute resource X"; there's an up-front calculation of the max # datatokens needed; the consumer sends that # datatokens to the publisher; the publisher does the computation/work; the publisher sends back the "change", ie datatokens not spent. This is what Alex suggested with "When starting compute, specify no of slots (hours, etc) and transfer that amount of tokens". This is possible with Ocean backend tech today. For frontend: publishers can publish in Ocean Market; and consumers can purchase the datatokens there too. Just the consume side would need to be a bit special; e.g. would require changes to Ocean Provider (or is there a simpler way @alexcos20 ?)

2. **ERC20, approve upper bound estimate.** Like (1) but use approve/transferFrom. That is: One solution using existing ERC20 setup is "1 datatoken gives you 1 min worth of compute resource X"; there's an up-front calculation of the max # datatokens needed; the consumer signs an `approve()` to the publisher to get those datatokens; the publisher does the computation/work; the publisher signs a `transferFrom()` for the tokens actually used; the consumer resets `approve()` to zero.

3. **ERC20 streaming payment.** Like (1) but the datatokens stream over time. This is what I suggested with "Use superfluid or otherwise for streaming payments over time". It will be far easier to do after Ocean V4 is released, because that allows other ERC20 datatoken templates. Re concern "in the middle of the execution the payment wallet could be empty and that would screw the reward for the contributors" -- Superfluid streaming approach addresses this issue.

4. **General streaming payments.** Represent base IP as ERC721, have some _non_-"ERC20 datatoken" means to stream payment to the holder of the base IP. This will be far easier to do after Ocean V4 , because it will have ERC721 to represent base IP.
