### ISSUE TITLE
Fetch.ai: Update to use the testnets

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/multi-repo-issue#140]
This issue is to update the `oceansimpleseller` and `oceanend2end` repos to use test networks.

Fetch.ai Capricorn testnet info can be found here: https://docs.fetch.ai/ledger_v2/networks/

**Comment by DMats** [comment]
I tried out the `oceansimpleseller` today. But I ran into difficulty while running the `run_ocean_seller.sh` script. The issue seems to be that I cannot successfully run `aea init` to create an AEA Registry account and create the AEA configuration files locally.

I sent messages to the Datarella team via Slack to see if they know what I'm doing wrong.
