### ISSUE TITLE
Make it easy to find/add "Projects using Ocean" info

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/multi-repo-issue#60]
Goal: we want to make it easy for the community to share what integrations they've had with Ocean, without the core team being a big bottleneck, yet with some degree of prominence. And for others to find that list of integrations.

Possible approaches: 
1. In docs, have a new page that has "Projects Using Ocean". Don't change main site.
2. In docs and in site, have a single-liner says "Projects using ocean". This links to a .md file in github, that is easy for people to change. (In the docs/ repo?)
3. Like (2) but a wiki rather than an md file. Note: OceanDAO wiki has worked out well, GitHub has much better wiki support than it used to.

Quick analysis (by Trent):
* (1) is a bit prettier, but also a bit more risky (what if docs breaks) and harder to maintain (it takes a while for the docs build to update)
* (2) is more lightweight, not risky, easy to maintain, easier for people to contribute
* (3) is like (2) but even easier for people to contribute.
* So I lean towards (3)

**Comment by trentmc** [comment]
I woke up realizing: *if* we do a wiki, it's best to be in its own repo. Why: 
* As a mental model, these lists are not *documentation* per se; they are community contributed content that can grow. 
* We want to give maximum breathing space for the community to grow out the content, to let it blossom.
* This makes them their own atomic "chunk" of content with different properties than `docs` or `site` - easier to change rapidly and expand in volume. They can and will be linked from docs and site and external parties too.
* Addresses @kremalicious concern: "introduce a second documentation system (rendered docs + repo wiki)". So by keeping them out of docs, we don't confuse the role of docs. BTW this would have even been an issue even if it wasn't a wiki.
* Addresses @kremalicious concern even better: "We can't add every external user who wants to edit the page to this repo." Whole new repo = permissions specific for that repo.
* Addresses @kremalicious concern: "creating a wiki on the repo makes that page harder to find compared to when it is in the rendered docs". Addressed because it's not *part* of docs, it is now its own thing.

So I moved the wiki from `docs` repo to a new `wiki` repo. I chose "wiki" to give flexibility to other future community content too; the lists are an obviously useful starting point. 
https://github.com/oceanprotocol/wiki/wiki/Projects-Using-Ocean

**Comment by kremalicious** [comment]
> Make it easy to find...

We should specify this, what does it mean? To me this implies good SEO so the definition of this should be "when people google 'projects using ocean'" and then optimize for it. None of that is solved by using a repo's wiki section. Our docs are perfectly indexed and show up high on Google, so it would be only a matter of using the right keywords within the text and URLs. Adding a projects page there also benefits the overall docs by bringing more traffic to it. A repository's wiki, especially a new one in that sense is hidden. We can only make people find it by linking to it from the docs which still doesn't help search engine users. But if users are already on the docs, why would we send them away to another place again? We either have a wiki documenting things, or we have our docs page. Having both just creates more noise and friction by valuing our developer experience more than our user's experience. Likewise, we need to enforce some consistent syntax and styling, otherwise we end up editing after each external edit. If public editing gets abused we have no way of adopting the workflow to that, and can only turn off public editing. Again, we cannot pay for every user who wants to edit the wiki, so we need to make it full public editing if the advantages presented for wiki should be met

> As a mental model, these lists are not documentation per se; they are community contributed content that can grow.

This also was the goal of the port, and people actually still use it https://port.oceanprotocol.com So grow this instead of introducing yet another system if we really want a place for community-generated content. The entry barriers for users are also lower there, creating and setting up a GitHub account is a lot of hazzle for non-devs. And if they already have a GitHub account then it's also easy to click the edit link at the end of each doc's page, making them community-maintained too

**Comment by trentmc** [comment]
Thanks for the thoughts 😊

> Make it easy to find...

To dis-ambiguate, there are two things here:

1. Find the page (or pages) that list the projects, coming from the broader internet
2. When at those pages, easily see which projects they are

You raise a good point about (1). However you also mention a solution: link to it from docs. (And we'd also link from Ocean homepage, etc). Why? This is a different beast than docs. Docs is for usage by developers, "Projects Using Ocean" is for the whole community. Docs is tightly controlled by core sw devs so that the experience stays optimal, "Projects Using Ocean" should be as openly editable as possible to allow its content to blossom. If there is abuse, we can evolve the rules over time, just as other wikis do as they mature.

> so we need to make it full public editing if the advantages presented for wiki should be met

Yes this is what we want! :) 

The github ui for setting wiki permissions is a bit confusing. Have I opened them up that way already? If not, let's do it.

> community contributed content that can grow.
> This also was the goal of the port, and people actually still use it https://port.oceanprotocol.com 

Yes both a forum and a wiki are community-contributed content. Yet forums and wikis are, kinda by definition, different tools with different target use cases. The former is meant, as a forum where the content is accreted in a time based fashion, with an emphasis on comments and discussion. The latter is meant for content where readers don't have to wade through comment after comment to get the essential info; this content is continually refined. As an example: in reading a Wikipedia article, you don't go through all the historical comments to understand it; and it wouldn't make much sense to argue that Wikipedia content should be placed into a forum-like tool.

However - and I think you're implicitly aiming for this - we want to keep the # tools / sites put out by the core team to a minimum, so as to minimize confusion by users. Having one more site - a wiki - goes against this. So we can ask which existing tool / site can be adapted to hold this. Or we can bite the bullet and have a new one, because nothing else is quite a fit. So far I've been doing the latter but I'm open to suggestions.

If you like -- perhaps we should have a quick call to discuss?

**Comment by kremalicious** [comment]
Just see what's more user friendly:

1. one page in our prominent docs https://betadocs.oceanprotocol.com/concepts/projects-using-ocean

OR

2. 5 pages with repetitive content split up in a wiki within a repo on GitHub

**Comment by trentmc** [comment]
There is user-friendly to (1) read, and (2) user-friendly to add projects.

(1) - tie between docs and wiki, imo
(2) - no contest, wiki is far better

We want the community to contribute content, and let this thing blossom.

And

**Comment by trentmc** [comment]
I thought more about this. 

For (1) - docs is easier to read. Wiki is ok, but docs is easier.

Let's say we go with docs. Then the Q is: how to optimize to "make it easy for the community to share what integrations they've had".

A first idea: at the top of the page, give a list of steps (with links) of how to contribute to the page. It amounts to doing a PR etc.

Thoughts?

**Comment by kremalicious** [comment]
but a wiki within a GitHub repo has the same hurdles as editing the docs. If you want to detach that in true wiki style from a GitHub account then we need to run our own wiki software or use external service so comparing docs and wiki is not fully working here cause of the differences between a stand-alone wiki and the wiki functionality of each GitHub repo. That's my point, if we require a GitHub account to edit the wiki, then it's trivial to rather edit a page in the docs where we have way better room for more automated guidelines during the edit process.

> Docs is tightly controlled by core sw devs so that the experience stays optimal

yes, automated. We could introduce auto-merging when checks pass if that's an issue. So far nobody from outside had problems editing the docs.

**Comment by trentmc** [comment]
> A first idea: at the top of the page, give a list of steps (with links) of how to contribute to the page. It amounts to doing a PR etc.
> Thoughts?

**Comment by trentmc** [comment]
In the PR, I gave a [proposal](https://github.com/oceanprotocol/docs/pull/521#issuecomment-765157385) to move this forward. How does that sound @kremalicious ?
