### ISSUE TITLE
[EPIC] Ocean Market can see data assets on both Polygon and Eth mainnet

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/multi-repo-issue#67]
**Summary**

Precursor issue: [deploy to polygon](https://app.zenhub.com/workspaces/ocean-main-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/multi-repo-issue/77).

Needs for this issue:
 * (a) Ocean Market can see data assets on both Polygon and Eth mainnet, at once. When they operate on an asset, it's specific for one chain.
 * (b) Includes Aquarius caching data across both chains

----

**Details: Ocean Market visibility**
- With Ocean Aquarius having metadata across >1 chains, Ocean Market could readily display the data assets across all chains. 
- For each data asset, it would also display which chain that asset came from. 
- When someone wants to transact on a given datatoken, they would select the appropriate network in the metamask dropdown. 
- There will likely be other gotchas and tweaks needed, but right now it feels like those will be small.

**Details: metadata**
- Each chain stores metadata on the chain as currently done. We _don't_ need to resort to a unified metadata store like arweave. 
- Ocean Aquarius gets changed to grab metadata from a *list* of chains, rather than a single chain. This is a logical extension of its current behavior, and not a huge change.  It would store an extra field to remember which chain the data asset came from.

**Details: outside scope of _this_ issue**

- Bridging datatokens across chains: See [multi-repo-issue#94](https://github.com/oceanprotocol/multi-repo-issue/issues/94).
- Cross-chain liquidity

**Comment by mihaisc** [comment]
This comment is WIP.
**Usage**
Aquarius will index assets from all the chains and add the `chainId` prop to the ddo. In the market we will see all the assets and we will be able to filter by chain if needed.
We can show the chain in the asset teaser or just in the asset details.
![image](https://user-images.githubusercontent.com/26000280/111448478-1fa77d80-8717-11eb-946c-5d9d65e8864a.png)
The wallet will not be relevant except when you want to interact with the chain.
![image](https://user-images.githubusercontent.com/26000280/111448991-a3fa0080-8717-11eb-859b-84d42d685669.png)
Pool/Trade tabs will have the same functionality.

When publishing we need to have a label to inform the user of the network the wallet is connected ( so he doesn't forget or do a mistake). The asset will be published on the network the wallet is connected.

For history we can either query all the graph ulrs and then merge them. Or i suggest to have a network switcher and show history for one network at a time.  Not sure if we want to spend more effort here at this time since the '>1 pools' will split this page.

Mainnet will be separate from test. So we will have eth main + polygon main and rinkeby + ropsten.
![image](https://user-images.githubusercontent.com/26000280/111450566-318a2000-8719-11eb-8440-ad79552f2ab2.png)


**Changes needed**

Biggest change will be in aquarius. Aquarius needs to sync all supported chains into one db. Is it possible to have multiple indexers that connect to the same db? (one for eth main and one for polygon main) @alexcos20 is this doable?

Ocean.js will have no changes.

In the market we need to remove the `OceanProvider` from wrapping all the site. It will wrap only `AssetActions` and `History`.

We need another endpoint to calculate the TVL footer, basically it's a sum of all the chains. 

The Graph will stay as it is.

**Comment by trentmc** [comment]
A small comment..

> Aquarius will index assets from all the chains and add the chainId prop to the ddo

I think you may need both chainId _and_ networkId. One on its own doesn't uniquely specify the chain. (A good design would only need one, but it's like this for historical reasons dating back to the ETC split. [Ref1](https://ethereum.stackexchange.com/questions/37533/what-is-a-chainid-in-ethereum-how-is-it-different-than-networkid-and-how-is-it/37536#:~:text=Network%20identifier%20(networkID)%20protects%20a,are%20synchronizing%20with%20other%20networks.&text=Chain%20identifier%20(chainID)%20introduced%20in,being%20included%20into%20another%20chain.) [Ref2](https://medium.com/@pedrouid/chainid-vs-networkid-how-do-they-differ-on-ethereum-eec2ed41635b))

Note that [market#431](https://github.com/oceanprotocol/market/issues/431) _does_ uniquely specify both chainId and networkId, though with the human readable names (vs integers). Either works. See https://chainid.network/ to see all the values side by side.

**Comment by trentmc** [comment]
> For history we can either query all the graph ulrs and then merge them. Or i suggest to have a network switcher and show history for one network at a time. Not sure if we want to spend more effort here at this time since the '>1 pools' will split this page.

I recommend to _not_ do this for this ticket, given the '>1 pools' split.

**Comment by mihaisc** [comment]
I updated the comment accordingly. The network switcher proposed is not that hard to implement since it will reuse the components we have. We need to have something there because we can't just remove all that functionality until `>1 pool`

**Comment by alexcos20** [comment]
I lean towards using only chainId.  (this is specified in genesis.json and EIP-155).   NetworkId is just used in inter-node comm.

**Comment by trentmc** [comment]
> I lean towards using only chainId. (this is specified in genesis.json and EIP-155). NetworkId is just used in inter-node comm.

Ok with me.

**Comment by alexcos20** [comment]
A DDO document is composed of standard DDO attributes:

@context
id
created
updated
publicKey
authentication
proof
verifiableCredential
dataToken
service

Until now, dataToken was a string, containing the deployed address of that datatoken contract.
What if, instead of being a string, could be an array that looks like:

{
[ chainId: 0x1, dataToken: 0x12323],
[ chainId: 0x2, dataToken: 0x456]
}
This will help us in bridging assets between networks. Same asset, with different bridged dataTokens

**Comment by trentmc** [comment]
🔥🔥
