### ISSUE TITLE
Test bridge and document for users

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/multi-repo-issue#78]
Related to #77 
Test bridge to make sure it works for ocean tokens and do a quick documentation for user on how to use it (maybe it already is)

https://wallet.matic.network/

This evolved into a docs update as well :
- [x] create bridge tutorial in "Bridges" section ( there will be multiple bridges as we expand on multiple chains)
- [x] add new network to Supported Networks https://docs.oceanprotocol.com/concepts/networks/ with all the basic info
- [x] mention and link to tutorial from the Supported Networks block

Also i suggest merging all the docs prs when we have the market actually running on the network

**Comment by kremalicious** [comment]
To further specify this, in docs:

- add to _Supported Networks_ https://docs.oceanprotocol.com/concepts/networks/ with all the basic info
- if there is no external bridge tutorial, create one maybe under the _Wallets_ section https://docs.oceanprotocol.com/tutorials/introduction/
- mention and link to tutorial from the  _Supported Networks_ block

**Comment by mihaisc** [comment]
This is not the doc task, that is done after all the other points are done. There will be another task in the docs for what you described

**Comment by DimitarSD** [comment]
@trentmc @mihaisc The Matic's bridge is really easy to use and very straightforward in terms of steps. However, since the testing is happening on the Mainnet the transfers (from Ethereum to Matic) requires gas (it was around $17, now it's around $22). I didn't take that into consideration yesterday, and I currently don't have any Ocean tokens or Eth to test with. Might be better if someone else does the test cuz otherwise we'll pay double the gas costs just for transferring and testing with an account of my own. Any suggestions on this block?

**Comment by trentmc** [comment]
It's not a huge cost compared to the grand scheme of things. Better that you (@DimitarSD) take care of all.

To proceed, I recommend to talk to @daneklustig or @brucepon about sending you some OCEAN or ETH to test with.

**Comment by daneklustig** [comment]
I have send @DimitarSD 100 OCEAN and 0.055 ETH for testing
Here is the ETH transaction - https://etherscan.io/tx/0x480f611215dac0205854c2ae1c3385ea95c30bb44a602aedee3a8f677a8385f6
Here is the OCEAN transaction - https://etherscan.io/tx/0x016aa0093cc80f0d39b7b3fd3e7b1266e48ecd163b74ec17022f11fdb71b2bd9

**Comment by DimitarSD** [comment]
OCEAN (ETH) -> OCEAN (MATIC)

Ethereum:
1) [tx/0xee0b3d5218005e128247d6cee4cb66ad7de156b0c6c1ececd64b78beaa48efd6](https://etherscan.io/tx/0xee0b3d5218005e128247d6cee4cb66ad7de156b0c6c1ececd64b78beaa48efd6)
2) [tx/0x1b26d057cd76daca56f3fead8c1dbb50b4173e26d245c712831f20ebef76cfa4](https://etherscan.io/tx/0x1b26d057cd76daca56f3fead8c1dbb50b4173e26d245c712831f20ebef76cfa4)

Matic:
3) [tx/0xc606901e4f5e0cd897738f2beb5ab04ac436b86ee5b2e753407a376818c9888e/token-transfers](https://explorer-mainnet.maticvigil.com/tx/0xc606901e4f5e0cd897738f2beb5ab04ac436b86ee5b2e753407a376818c9888e/token-transfers)

OCEAN (MATIC) -> OCEAN (ETH): WIP, fees are too high at the moment

**Comment by DimitarSD** [comment]
This is the short guide (I wasn't sure where to share the full version). There are images too, but I didn't add them here. I mainly followed the style format from the documentation.

-------

# Bridges

## Matic’s Bridge

The Matic Network has its own [wallet](https://wallet.matic.network) that connects to your account via Metamask (or any of the other supported wallets). Once you open the link, the wallet will ask to log in. Select your preferred way of connecting and confirm the action.

### Deposit Tokens

On the main page of the wallet, you can see all tokens you own on the Matic Mannet. To deposit tokens (transfer them from the Ethereum Mainnet) you can either use the “deposit” button for a selected token or use “Move funds to Matic Mainnet”. Both options will redirect you to the bridge interface. In case you chose the second one, use the dropdown and select the token you want to transfer from the Ethereum Mainnet.

Choose the amount to transfer and click the “Transfer” button. Matic’s bridge interface will guide you through the whole process and the different steps that will occur. You’ll need to sign two transactions on the Ethereum Mainnet. The first being the approval for your token to be traded on the Matic’s bridge and the second one being the deposit.

### Withdraw Tokens

The withdrawing tokens process uses the same bridge interface. The only difference being that the withdraw happens from the Matic to the Ethereum Mainnet. 

Again the bridge interface will guide you through the different steps. 

For more in dept explanation of the deposit and withdraw actions check this [link](vhttps://docs.matic.network/docs/develop/ethereum-matic/pos/getting-started)

### Sending Tokens

While in the first two cases, the transactions are signed on the Ethereum Mainnet, transferring tokens between two Matic addresses happens on the Matic Mainnet. Thus it’s required for you to connect to the Matic network to sign the transactions. You can use the following parameters to set the network in Metamask:

**Network Name:** Matic Mainnet
**RPC:** https://rpc-mainnet.maticvigil.com/
**Chain Id:** 137
**Currency Symbol:** MATIC
**Block Explorer URL:** https://explorer.matic.network/

*Note: If you receive a 500 error “Rate limit exceeded” while you’re trying to transfer tokens on the Matic network, don’t worry. That happens because the public RPC provided by Matic has a daily rate limit of 50K hits. Once the daily limit is reset you’ll be able to use the RPC again.*

-------

Also, there are a few questions that we’ll need clear:

1. Should we use Matic or Polygon? In a lot of places, they’re still using the first name, and if we start using Polygon it might be confusing for the users (especially in the beginning). 
2. I added a note at the end regarding the 500 error. However, I'm not sure if we should focus on resolving the issue entirely or have a fallback plan. Since it's a [public RPC](https://docs.matic.network/docs/develop/metamask/config-matic/#matic-mainnet) it comes from Matic, and they maintain it.

**Comment by trentmc** [comment]
> This is the short guide (I wasn't sure where to share the full version).

You'll want it in docs.oceanprotocol.com.

Perhaps in https://docs.oceanprotocol.com/concepts/networks/, or in a new page that follows that page, depending on the amount of content.

> Should we use Matic or Polygon?

I'd suggest to say both for now. E.g. "Polygon (was Matic)". 

> rate limit note

We need to fix this rather than just have a note.

**Comment by DimitarSD** [comment]
In the docs, we have [links](https://docs.oceanprotocol.com/concepts/networks/#mainnet) to where we can purchase OCEAN tokens (on the Ethereum Mainnet). But I got quite confused with Matic Mainnet (or even any future network). We’re going to have one “main” OCEAN token across different chains. Is it going to be possible to purchase mOCEANS (the Matic's version) or all OCEAN tokens will come from the ETH Mainnet?

**Comment by trentmc** [comment]
> Is it going to be possible to purchase mOCEANS (the Matic's version) or all OCEAN tokens will come from the ETH Mainnet?

There's nothing stopping people from setting up DEXes and CEXes for mOCEANs. 

Being able to buy mOCEAN from an exchange would actually be super useful for Ocean Market users on Matic to avoid high Eth mainnet gas fees. 

We should look around to see what's already on Matic, and see if there's a first class DEX out there, and if there is, to make sure mOCEAN can be exchanged for. 

If we do this well, we should expect that most new users would never have to touch the Eth mainnet; their full experience would be on Matic.

(Over time we'll want fiat on/off ramps into mOCEAN too.)

**Comment by DimitarSD** [comment]
Got it! I'll update the docs accordingly. 

And one more thing. Not a high priority at the moment, but this [section](https://oceanprotocol.com/token#get) will need an update as we move forward and introducing new exchanges. Currently, it's being used (in the supported networks docs) for providing information for official exchanges to trade OCEAN. We'll need to have similar for mOCEAN or any future equivalent.

**Comment by trentmc** [comment]
Good point. And in fact I think it could become a priority quickly, for the reasons I give in my comment above. I recommend that you create a specific github issue to handle it. That is:
- We should look around to see what's already on Matic, and see if there's a first class DEX out there, and if there is, to make sure mOCEAN can be exchanged for.
- Link to it from ocean docs
- Link to it from ocean main site

**Comment by trentmc** [comment]
Is there anything preventing the closing of this issue? @DimitarSD

**Comment by DimitarSD** [comment]
Docs are ready, but the [PR #577](https://github.com/oceanprotocol/docs/pull/577) is not merged yet and the PR is connected to this issue. @mihaisc suggested merging all the docs PRs when the market is actually running on the Polygon network. Other than that - no.
