### ISSUE TITLE
ocean-contracts is hard to use in python, including in ocean.py

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/multi-repo-issue#83]
**Is your feature request related to a problem? Please describe.**
The [ocean-contracts repo](https://github.com/oceanprotocol/contracts) is available as a python package in pypi, [here](https://pypi.org/project/ocean-contracts/).

However it has issues:
1. The py usage itself is non-standard and surprising. Upon installing into a venv or python site package, you can't `import` it easily. Instead, you need to look into a special `artifacts/` directory (eg `venv/artifacts/`) with the .json files. Note: [ocean.js usage of ocean-contracts](https://github.com/oceanprotocol/ocean.py/issues/95#issuecomment-784074171) is an example of how it might be done cleanly.
1. ocean.py needs to use the non-standard setup given in (2). It's hard to understand, not documented, not tested, and likely brittle. See method `ocean_lib/config.py::artifacts_path()` reference to `site.PREFIXES` ([related py docs](https://docs.python.org/3/library/site.html#site.PREFIXES)).
1. The documentation on pypi is fully JS-centric; it has no info of how python developers might use `ocean-contracts` package.

This weirdness can lead to brittleness. It might be the root cause of  [ocean.py#144](https://github.com/oceanprotocol/ocean.py/issues/144) "Cannot Find Contract Address".

**Describe the solution you'd like**
- [x] Fix issue (1) above. 
- [x] Fix issue (2) above. This includes: (a) code is easy to understand, documented (if needed), tested, and more robust (b) remove the references to VIRTUAL_ENV and VIRTUAL_ENV artifacts path in ocean_lib/config.py which only serves to retrieve artifacts from there. (as mentioned in a comment below)
- [x] Fix issue (3) above. What can help: ["making a PyPI-friendly README"](https://packaging.python.org/guides/making-a-pypi-friendly-readme/)
- [x] Deploy all to pypi, test extensively, make sure it doesn't break other stuff
- [x] Update ocean.py to use this new setup. E.g. `from ocean_abis import address` etc, see [updated contracts README](https://github.com/oceanprotocol/contracts#readme)
- [x] See if this solves [ocean.py#144](https://github.com/oceanprotocol/ocean.py/issues/144https://github.com/oceanprotocol/ocean.py/issues/144)
- [x] Update Provider to use new setup, test well
- [x] Update Aquarius to use new setup, test well

**Background info**

This is the script to deploy ocean-contracts as a pypi library: https://github.com/oceanprotocol/contracts/blob/master/scripts/deploy_pypi.sh

It uses that repo's setup file: https://github.com/oceanprotocol/contracts/blob/master/setup.py

Which leads to the ocean-contracts pypi page: https://pypi.org/project/ocean-contracts/

Example of a plain install of ocean-contracts:

```console
trentmc@trentmcLnv:~/temp$ python -m venv venv
trentmc@trentmcLnv:~/temp$ source venv/bin/activate

(venv) trentmc@trentmcLnv:~/temp/venv$ ls 
bin  include  lib  lib64  pyvenv.cfg

(venv) trentmc@trentmcLnv:~/temp$ pip install ocean-contracts
Collecting ocean-contracts
  Downloading ocean_contracts-0.5.10-py2.py3-none-any.whl (611 kB)
     |----------------------------| 611 kB 3.8 MB/s 
Installing collected packages: ocean-contracts
Successfully installed ocean-contracts-0.5.10
```

You can't use ocean-contracts from importing in python code.
```python
trentmc@trentmcLnv:~/temp$ python
>>> import ocean_contracts
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'ocean_contracts'
>>> import contracts
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'contracts'
>>> import artifacts
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'artifacts'
```
Here's what an install puts into the directory.
```console
(venv) trentmc@trentmcLnv:~/temp$ cd venv/
artifacts/ bin/       include/   lib/       lib64/     
(venv) trentmc@trentmcLnv:~/temp$ cd venv/artifacts/
(venv) trentmc@trentmcLnv:~/temp/venv/artifacts$ ls -l
total 8476
-rw-r--r-- 1 trentmc trentmc    1965 Mar  1 15:54 address.json
-rw-r--r-- 1 trentmc trentmc  101358 Mar  1 15:54 BConst.json
```

Here's how ocean.py includes it, from ocean.py's setup.py file:
```
install_requirements = [
    "ocean-contracts==0.5.8",
```

Here's how ocean.py uses it.

`ocean_lib/config.py::artifacts_path()` is where it figures out where to grab the "artifacts", including from ocean-contracts pip library. More info on site.PREFIXES [is here](https://docs.python.org/3/library/site.html#site.PREFIXES)

```python
             path = os.path.join(site.PREFIXES[0], "artifacts")
             if not os.path.exists(path):
                 # try to find 'artifacts' in a subfolder of site.PREFIXES[0]
 ```

**Comment by calina-c** [comment]
Note: please remove the references to VIRTUAL_ENV and VIRTUAL_ENV artifacts path in ocean_lib/config.py which only serves to retrieve artifacts from there. [Discussed on Slack regarding test coverage]

**Comment by trentmc** [comment]
Note: doing this will help to prevent issues like ocean.py#185 and ocean.py#205 in the future

**Comment by trentmc** [comment]
Note: https://github.com/oceanprotocol/contracts/issues/276 is blocking this issue.

**Comment by trentmc** [comment]
> Note: oceanprotocol/contracts#276 is blocking this issue.

Update: This is fixed now. +1

**Comment by trentmc** [comment]
@0x3bfc is this issue complete? It's unclear. If complete, please close.

**Comment by 0x3bfc** [comment]
still working on a minor update, then will update the documentation. It should be done by today.

**Comment by DMats** [comment]
# Problem: jsonsempai doesn't reduce complexity if we continue to support ARTIFACTS_PATH
I raised an issue with @alexcos20 privately that I have struggled with this task because I've received instruction that ocean.py, aquarius, and provider need to support loading custom ABI JSON files from `ARTIFACTS_PATH` envvar or artifacts.path` config.ini option. This might have been used by 3rd parties operating on PoA networks with customized ocean contracts. 

This means that even though we have a new, cleaner `jsonsempai` method of loading JSON files, it requires that we know the json filenames ahead of time. So while the intention of this issue was to simplify the code, it has only resulted in more complexity, because we're supporting both the old and the new ways.

# How does ocean.js handle ABIs?
Upon hearing this, @alexcos20 explained that ocean.js always grabs the ocean ABIs from `node_modules/@oceanprotocol/contracts/artifacts/`. So if a 3rd party wanted to use custom ABI files, they'd have to install the @oceanprotocol/contracts npm package, and then edit/overwrite the files manually before running ocean.js.

# Are there any problems with this approach?
At first, this approach made me uneasy - manually editing a PyPi package after installing it seemed brittle.  But then I realized that if a 3rd party is using custom addresses and ABIs, they've probably already forked the ocean-contracts repo so I think it's fair to expect them to create a custom ocean-contracts package and to also fork ocean.py so that it uses their custom ocean-contracts package.  So I see no problems with this approach. 

# Benefits of this approach
The upside of this approach is that we can simplify the ocean.py codebase by eliminating:

1. JSON loading and validation for ocean ABIs. (Please note we'd still need JSON loading code for address.json, ADDRESS_FILE, and address.file)
2. ARTIFACTS_PATH envvar and artifacts.path config option
3. ContractHandler

This change could also simplify aquarius and provider because they, too, could eliminate the ARTIFACTS_PATH envvar (which was needed to initialize ContractHandler)

# Next Steps
I've added several checkboxes to this issue because I think the changes described above are within the scope of the original issue.  (Sorry, I know it's already super long, but it just didn't make sense to me to split it into a new issue)

**Comment by DMats** [comment]
I've also recently noticed that Provider contains copies of DataTokenTemplate.json and DTFactory.json. This should definitely be removed and it should be made to pull contract ABIs from ocean-contracts.  Just added this to the subtasks.

**Comment by trentmc** [comment]
I like the aims to reduce complexity, and the specific proposed tactics. This is promising. +1 from me to giving it a whirl.

**Comment by calina-c** [comment]
@DMats This issue is ancient and there's no visible scope to it anymore. I propose separating any new improvements for ocean-contracts into a different task. Can it be done? Nobody has the time to scroll through 4 screens of comments and updates, including those from 3 iterations ago, when the task was different.

CC @trentmc, do you agree?

**Comment by trentmc** [comment]
> I propose separating any new improvements for ocean-contracts into a different task. Can it be done? 

This is a good idea @calina-c . 

If it can be done, we should do it. @DMats ball's in your court.

**Comment by DMats** [comment]
@calina-c @trentmc I can definitely break this issue up.  Thanks for the guidance.

**Comment by DMats** [comment]
@calina-c @trentmc 
I broke the remaining tasks into three new issues and removed them from this issue.

https://github.com/oceanprotocol/ocean.py/issues/327
https://github.com/oceanprotocol/aquarius/issues/478
https://github.com/oceanprotocol/provider/issues/149
